"""
Модуль нормализации FB2 текста
"""

from normfb2.data import (
    CURRENCIES,
    DECIMAL_PLACES,
    EN_LETTER_NAMES,
    GREEK_LETTER_NAMES,
    GREEK_TO_RUSSIAN,
    LATIN_DIACRITICS_MAP,
    LETTER_NAMES,
    MONTHS_GEN,
    MULTIPLIERS,
    ORDINAL_CASES,
    SECTION_ABBR,
    SUFFIX_FORMS,
    SYMBOLS,
    VULGAR_FRACTIONS,
    WEB_SYMBOLS,
)
from normfb2.dicts import DIACRITIC_MAP, AcronymDict, replace_diacritics
from normfb2.roman import (
    CYRILLIC_TO_LATIN_ROMAN,
    RE_ROMAN,
    RE_ROMAN_VALID,
    ROMAN_STOPLIST,
    ROMAN_VALUES,
    is_valid_roman,
    ordinal_text,
    roman_to_int,
)
from normfb2.steps import (
    COMBINING_DIACRITICAL,
    PROTECT_MARKER_PREFIX,
    PROTECT_MARKER_SUFFIX,
    RUSSIAN_CHAR,
    TAG_EN_CLOSE,
    TAG_EN_OPEN,
    cyrillize,
    normalize_acronyms,
    normalize_alphanumeric,
    normalize_case_context,
    normalize_compounds,
    normalize_currency,
    normalize_dates,
    normalize_decimal_hyphen,
    normalize_decimals,
    normalize_fractions,
    normalize_greek,
    normalize_language_tags,
    normalize_measurements,
    normalize_measurements_1letter,
    normalize_multipliers,
    normalize_negatives,
    normalize_number_groups,
    normalize_numbers,
    normalize_ordinal_suffixes,
    normalize_percent,
    normalize_ranges,
    normalize_regex_dict,
    normalize_roman_generic,
    normalize_rulers,
    normalize_sections,
    normalize_symbols,
    normalize_time,
    normalize_typography,
    normalize_web,
    restore_protected,
    transliterate_latin_diacritics,
)
from normfb2.utils import (
    NormalizationLogger,
    StatsCollector,
    _feminine_last,
    _plural,
    apply_step,
    detokenize_words_gaps,
    find_replacements,
    number_to_words,
    tokenize_words_gaps,
)

